name: RDP Desktop

on:
  workflow_dispatch:

jobs:
  desktop:

    runs-on: ubuntu-latest

    timeout-minutes: 360

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install Desktop
      run: |
        sudo apt update
        sudo DEBIAN_FRONTEND=noninteractive apt install -y \
          xfce4 \
          xfce4-goodies \
          dbus-x11 \
          xrdp \
          xorgxrdp


    - name: Configure XFCE
      run: |

        echo "startxfce4" > ~/.xsession

        sudo mkdir -p /etc/skel

        echo "startxfce4" | sudo tee /etc/skel/.xsession

        sudo sed -i 's/startwm.sh/startwm.sh/' /etc/xrdp/startwm.sh

        sudo systemctl enable xrdp || true



    - name: Create RDP User
      run: |

        sudo useradd -m -s /bin/bash rdpuser || true

        echo "rdpuser:123456" | sudo chpasswd

        sudo usermod -aG ssl-cert rdpuser

        echo "startxfce4" | sudo tee /home/rdpuser/.xsession

        sudo chown rdpuser:rdpuser /home/rdpuser/.xsession



    - name: Install Tailscale
      run: |

        curl -fsSL https://tailscale.com/install.sh | sh



    - name: Connect Tailscale
      env:
        TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}

      run: |

        sudo tailscale up --authkey=$TS_AUTHKEY

        echo "TAILSCALE IP:"
        tailscale ip -4



    - name: Restart XRDP
      run: |

        sudo systemctl restart xrdp || true

        sudo systemctl restart xrdp-sesman || true



    - name: Check Server
      run: |

        echo "USER:"
        echo rdpuser

        echo "PASSWORD:"
        echo 123456

        echo "IP:"
        tailscale ip -4

        echo "XRDP:"
        ps aux | grep xrdp || true

        echo "PORT:"
        ss -tlnp | grep 3389 || true



    - name: Keep Server Alive
      run: |

        while true
        do
          echo "RDP SERVER RUNNING"
          date
          sleep 300
        done
